apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: es-pxl
  labels:
    backup.eventstreams.ibm.com/component: eventstreams
  namespace: id-pxl-poc
spec:
  license:
    accept: true
    license: L-HRZF-DWHH7A
    use: EventAutomationNonProduction
  strimziOverrides:
    kafka:
      config:
        inter.broker.protocol.version: '3.7'
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 3
        offsets.topic.replication.factor: 3
        default.replication.factor: 3
        min.insync.replicas: 2
      metricsConfig:
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: development-metrics-config
        type: jmxPrometheusExporter
      authorization:
        type: simple
      storage:
        type: ephemeral
      listeners:
        - authentication:
            type: scram-sha-512
          name: external
          port: 9094
          type: route
          tls: true
        - authentication:
            type: tls
          name: tls
          port: 9093
          type: internal
          tls: true
      replicas: 3
    zookeeper:
      metricsConfig:
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: development-metrics-config
        type: jmxPrometheusExporter
      storage:
        type: ephemeral
      replicas: 3
  adminUI:
    authentication:
      - type: scram-sha-512
  restProducer: {}
  apicurioRegistry: {}
  adminApi: {}
  collector: {}
  version: latest
