apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaUser
metadata:
  name: admin-pxl
  namespace: id-niki-pxl-poc
  labels:
    eventstreams.ibm.com/cluster: es-pxl
    backup.eventstreams.ibm.com/component: kafkauser
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: cluster
        operations:
          - All
          - Alter
          - AlterConfigs
          - ClusterAction
          - Create
          - Describe
          - IdempotentWrite
          - DescribeConfigs
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
          - Alter
          - AlterConfigs
          - Create
          - Delete
          - Describe
          - DescribeConfigs
          - Read
          - Write
      - resource:
          type: topic
          name: __schema_
          patternType: prefix
        operations:
          - Alter
          - Read
      - resource:
          type: group
          name: '*'
          patternType: literal
        operations:
          - All
          - Read
          - Delete
          - Describe
          
